import { useState } from "react";
import { Link } from "react-router-dom";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { useToast } from "@/components/ui/Toast";
import { useAuth } from "@/context/AuthContext";
import {
    FileText,
    Download,
    Calendar,
    Clock,
    FileSpreadsheet,
    File,
    Loader2,
    CheckCircle,
    TrendingUp,
    Users,
    DollarSign,
    AlertTriangle,
} from "lucide-react";

// Demo report data
const REPORT_HISTORY = [
    {
        id: 1,
        name: "Weekly Transaction Summary",
        type: "weekly",
        date: "2024-12-01",
        size: "2.4 MB",
        status: "ready",
    },
    {
        id: 2,
        name: "Monthly Performance Report",
        type: "monthly",
        date: "2024-11-30",
        size: "5.1 MB",
        status: "ready",
    },
    {
        id: 3,
        name: "Weekly Transaction Summary",
        type: "weekly",
        date: "2024-11-24",
        size: "2.2 MB",
        status: "ready",
    },
    {
        id: 4,
        name: "Churn Risk Analysis Q4",
        type: "quarterly",
        date: "2024-11-15",
        size: "8.3 MB",
        status: "ready",
    },
];

export function Reports() {
    const { user } = useAuth();
    const { success } = useToast();
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatingType, setGeneratingType] = useState<string | null>(null);

    const handleGenerateReport = async (type: string) => {
        setIsGenerating(true);
        setGeneratingType(type);

        // Simulate report generation
        await new Promise((r) => setTimeout(r, 2000));

        // Generate and download the report
        generateReportFile(type);

        success("Report Generated", `Your ${type} report is ready for download`);
        setIsGenerating(false);
        setGeneratingType(null);
    };

    const generateReportFile = (type: string) => {
        const date = new Date().toISOString().split("T")[0];
        const reportContent = generateReportContent(type);

        const blob = new Blob([reportContent], { type: "text/csv" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `transactiq_${type}_report_${date}.csv`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    const generateReportContent = (type: string): string => {
        const header = "TransactIQ Analytics Report\n";
        const generatedDate = `Generated: ${new Date().toLocaleString()}\n`;
        const reportType = `Report Type: ${type.charAt(0).toUpperCase() + type.slice(1)}\n`;
        const org = `Organization: ${user?.organization || "Demo Organization"}\n\n`;

        const summaryHeader = "=== EXECUTIVE SUMMARY ===\n\n";
        const kpis = `Key Performance Indicators,Value,Change\n` +
            `Total Transaction Volume,1247853,+7.9%\n` +
            `Total Revenue,$45.7M,+8.3%\n` +
            `Active Merchants,3847,+5.3%\n` +
            `Churn Rate,2.4%,-22.6%\n` +
            `Average Transaction,$36.60,+0.4%\n\n`;

        const revenueHeader = "=== REVENUE BY CATEGORY ===\n\n";
        const revenueData = `Category,Revenue,Percentage\n` +
            `Retail,$12.45M,27.3%\n` +
            `Food & Beverage,$9.87M,21.6%\n` +
            `Electronics,$8.34M,18.3%\n` +
            `Healthcare,$6.12M,13.4%\n` +
            `Travel,$5.23M,11.5%\n` +
            `Other,$3.66M,8.0%\n\n`;

        const churnHeader = "=== CHURN RISK SUMMARY ===\n\n";
        const churnData = `Merchant,Category,Risk Score,Risk Level,Days Inactive\n` +
            `TechStyle Electronics,Electronics,87%,Critical,45\n` +
            `Gourmet Delights,Food & Beverage,73%,High,28\n` +
            `Urban Threads,Retail,65%,High,21\n` +
            `Wellness Hub,Healthcare,52%,Medium,14\n` +
            `Quick Mart Express,Retail,48%,Medium,12\n\n`;

        const topMerchantsHeader = "=== TOP PERFORMING MERCHANTS ===\n\n";
        const topMerchants = `Merchant,Transactions,Revenue,Trend\n` +
            `Fresh Foods Market,32456,$892300,+12.3%\n` +
            `Coffee Central,24567,$134500,+2.1%\n` +
            `Quick Mart Express,18765,$156780,-5.2%\n` +
            `Gourmet Delights,12340,$285600,-25.8%\n` +
            `Urban Threads,9876,$198400,-22.1%\n\n`;

        const footer = "\n=== END OF REPORT ===\n" +
            "Generated by TransactIQ Analytics Platform\n" +
            "For questions, contact support@transactiq.io";

        return header + generatedDate + reportType + org +
            summaryHeader + kpis +
            revenueHeader + revenueData +
            churnHeader + churnData +
            topMerchantsHeader + topMerchants +
            footer;
    };

    const handleDownloadReport = (reportId: number) => {
        const report = REPORT_HISTORY.find((r) => r.id === reportId);
        if (report) {
            generateReportFile(report.type);
            success("Downloading", `${report.name} is being downloaded`);
        }
    };

    return (
        <div className="space-y-6">
            {/* Page Header */}
            <div>
                <h1 className="text-3xl font-bold tracking-tight flex items-center gap-2">
                    <FileText className="h-8 w-8 text-primary" />
                    Reports & Analytics
                </h1>
                <p className="text-muted-foreground">
                    Generate and download comprehensive analytics reports
                </p>
            </div>

            {/* Quick Stats */}
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                <Card className="glass-card">
                    <CardContent className="pt-6">
                        <div className="flex items-center gap-3">
                            <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                                <TrendingUp className="h-5 w-5 text-primary" />
                            </div>
                            <div>
                                <p className="text-sm text-muted-foreground">Total Volume</p>
                                <p className="text-xl font-bold">1.2M</p>
                            </div>
                        </div>
                    </CardContent>
                </Card>
                <Card className="glass-card">
                    <CardContent className="pt-6">
                        <div className="flex items-center gap-3">
                            <div className="w-10 h-10 rounded-lg bg-success/10 flex items-center justify-center">
                                <DollarSign className="h-5 w-5 text-success" />
                            </div>
                            <div>
                                <p className="text-sm text-muted-foreground">Revenue</p>
                                <p className="text-xl font-bold">$45.7M</p>
                            </div>
                        </div>
                    </CardContent>
                </Card>
                <Card className="glass-card">
                    <CardContent className="pt-6">
                        <div className="flex items-center gap-3">
                            <div className="w-10 h-10 rounded-lg bg-indigo-500/10 flex items-center justify-center">
                                <Users className="h-5 w-5 text-indigo-500" />
                            </div>
                            <div>
                                <p className="text-sm text-muted-foreground">Merchants</p>
                                <p className="text-xl font-bold">3,847</p>
                            </div>
                        </div>
                    </CardContent>
                </Card>
                <Card className="glass-card">
                    <CardContent className="pt-6">
                        <div className="flex items-center gap-3">
                            <div className="w-10 h-10 rounded-lg bg-warning/10 flex items-center justify-center">
                                <AlertTriangle className="h-5 w-5 text-warning" />
                            </div>
                            <div>
                                <p className="text-sm text-muted-foreground">At Risk</p>
                                <p className="text-xl font-bold">12</p>
                            </div>
                        </div>
                    </CardContent>
                </Card>
            </div>

            {/* Generate Reports */}
            <Card className="glass-card">
                <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                        <Download className="h-5 w-5" />
                        Generate New Report
                    </CardTitle>
                </CardHeader>
                <CardContent>
                    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                        <Button
                            variant="outline"
                            className="h-auto py-6 flex flex-col gap-2"
                            onClick={() => handleGenerateReport("weekly")}
                            disabled={isGenerating}
                        >
                            {isGenerating && generatingType === "weekly" ? (
                                <Loader2 className="h-6 w-6 animate-spin" />
                            ) : (
                                <Calendar className="h-6 w-6 text-primary" />
                            )}
                            <span className="font-semibold">Weekly Summary</span>
                            <span className="text-xs text-muted-foreground">Last 7 days analytics</span>
                        </Button>
                        <Button
                            variant="outline"
                            className="h-auto py-6 flex flex-col gap-2"
                            onClick={() => handleGenerateReport("monthly")}
                            disabled={isGenerating}
                        >
                            {isGenerating && generatingType === "monthly" ? (
                                <Loader2 className="h-6 w-6 animate-spin" />
                            ) : (
                                <FileSpreadsheet className="h-6 w-6 text-success" />
                            )}
                            <span className="font-semibold">Monthly Report</span>
                            <span className="text-xs text-muted-foreground">Full month breakdown</span>
                        </Button>
                        <Button
                            variant="outline"
                            className="h-auto py-6 flex flex-col gap-2"
                            onClick={() => handleGenerateReport("churn")}
                            disabled={isGenerating}
                        >
                            {isGenerating && generatingType === "churn" ? (
                                <Loader2 className="h-6 w-6 animate-spin" />
                            ) : (
                                <AlertTriangle className="h-6 w-6 text-warning" />
                            )}
                            <span className="font-semibold">Churn Analysis</span>
                            <span className="text-xs text-muted-foreground">At-risk merchants</span>
                        </Button>
                        <Button
                            variant="outline"
                            className="h-auto py-6 flex flex-col gap-2"
                            onClick={() => handleGenerateReport("custom")}
                            disabled={isGenerating}
                        >
                            {isGenerating && generatingType === "custom" ? (
                                <Loader2 className="h-6 w-6 animate-spin" />
                            ) : (
                                <File className="h-6 w-6 text-indigo-500" />
                            )}
                            <span className="font-semibold">Custom Report</span>
                            <span className="text-xs text-muted-foreground">Build your own</span>
                        </Button>
                    </div>
                </CardContent>
            </Card>

            {/* Report History */}
            <Card className="glass-card">
                <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                        <Clock className="h-5 w-5" />
                        Report History
                    </CardTitle>
                </CardHeader>
                <CardContent>
                    <div className="space-y-3">
                        {REPORT_HISTORY.map((report) => (
                            <div
                                key={report.id}
                                className="flex items-center justify-between p-4 rounded-xl border bg-muted/30 hover:bg-muted/50 transition-colors"
                            >
                                <div className="flex items-center gap-4">
                                    <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                                        <FileText className="h-5 w-5 text-primary" />
                                    </div>
                                    <div>
                                        <p className="font-medium">{report.name}</p>
                                        <div className="flex items-center gap-3 text-sm text-muted-foreground">
                                            <span>{new Date(report.date).toLocaleDateString()}</span>
                                            <span>•</span>
                                            <span>{report.size}</span>
                                        </div>
                                    </div>
                                </div>
                                <div className="flex items-center gap-3">
                                    <Badge variant="secondary" className="capitalize">
                                        {report.type}
                                    </Badge>
                                    <Badge variant="success" className="flex items-center gap-1">
                                        <CheckCircle className="h-3 w-3" />
                                        Ready
                                    </Badge>
                                    <Button
                                        variant="outline"
                                        size="sm"
                                        onClick={() => handleDownloadReport(report.id)}
                                    >
                                        <Download className="h-4 w-4 mr-1" />
                                        Download
                                    </Button>
                                </div>
                            </div>
                        ))}
                    </div>
                </CardContent>
            </Card>

            {/* Schedule Reports */}
            <Card className="glass-card border-primary/30">
                <CardContent className="py-6">
                    <div className="flex items-center justify-between">
                        <div>
                            <h3 className="font-semibold">Automated Report Scheduling</h3>
                            <p className="text-sm text-muted-foreground">
                                Set up automatic weekly or monthly reports delivered to your email
                            </p>
                        </div>
                        <Link to="/settings">
                            <Button>Configure Schedule</Button>
                        </Link>
                    </div>
                </CardContent>
            </Card>
        </div>
    );
}
